spring:
  application:
    name: spring-cloud-eureka-client
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
resilience4j.circuitbreaker:
  instances:
    trainerbilling:
      registerHealthIndicator: true
      slidingWindowSize: 5
      minimumNumberOfCalls: 3
      failureRateThreshold: 50